name: e_commerce_app
description: "A new Flutter E‑Commerce App."
publish_to: 'none' # Prevent accidental publishing
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Network
  dio: ^5.9.0
  cached_network_image: ^3.2.3
  connectivity_plus: ^6.1.5

  # Database
  sqflite: ^2.2.8
  path: ^1.8.2
  shared_preferences: ^2.1.0

  flutter_svg: ^2.2.0
  flutter_screenutil: ^5.9.3

  # UI Components
  flutter_rating_bar: ^4.0.1
  shimmer: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_image_slideshow: ^0.1.6
  flutter_staggered_grid_view: ^0.7.0
  lottie: ^3.3.1
  photo_view: ^0.14.0
  flutter_slidable: ^3.0.1

  image_picker: ^0.8.7+5  # For selecting profile images
  path_provider: ^2.0.15  # For accessing app directory to save images

  share_plus: ^7.1.0

  # Utils
  intl: ^0.18.0
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/icons/png/
    - assets/icons/svg/
    - assets/images/categories/

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          weight: 700

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
          weight: 700

# Splash screen configuration (root level)
flutter_native_splash:
  color: "#FFF8E1"                # Light mode background color
  color_dark: "#1E1E1E"           # Dark mode background color
  image: "assets/icons/png/Shopify.png"
  ios_content_mode: center         # Center splash image on iOS
  android_gravity: center          # Center splash image on Android
  fullscreen: true                 # Force fullscreen splash screen
  android: true
  ios: true